export default {
    "1":{
        id:1,
        name:"Smashicons",
        type:"Attribution",
        linkUrl:"https://www.flaticon.com/authors/smashicons"
    },
    "2":{
        id:2,
        name:"Prateek",
        type:"Contributor",
        linkUrl:"https://github.com/enzi077"
    },
    "3":{
        id:3,
        name:"Wikipedia",
        type:"Attribution",
        linkUrl:"https://www.wikipedia.org/"
    }
}